include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ---- Naming Conventions ----
    camel_case_types: true
    file_names: true
    constant_identifier_names: false
    library_prefixes: true

    # ---- Code Style ----
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unnecessary_const: true
    unnecessary_this: true

    # ---- Error Prevention ----
    avoid_print: true   # ممنوع print → لازم Logger
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    avoid_init_to_null: true
    unnecessary_null_checks: true

    # ---- Readability ----
    sort_child_properties_last: true
    require_trailing_commas: true
    prefer_expression_function_bodies: true
    type_annotate_public_apis: true

analyzer:
  errors:
    avoid_print: error
    prefer_const_constructors: warning
    prefer_single_quotes: warning
    unnecessary_this: warning
