name: mamdouh_ahmed_portfolio
description: "A professional portfolio website built with Flutter, Supabase, and Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^16.2.1

  # Backend & Networking
  supabase_flutter: ^2.10.0
  dio: ^5.9.0

  # Data Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Animations & Graphics
  rive: ^0.13.20
  lottie: ^3.3.1

  # 3D
  model_viewer_plus: ^1.9.3
  flutter_cube: 0.1.1
  logger: ^2.6.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - .env.example
  #   - assets/images/
  #   - assets/rive/
  #   - assets/3d_models/
